### ISSUE TITLE
Colagrossi problem description and input are inconsistent

### ISSUE THREAD

**Issue by cekees** [erdc-cm/air-water-vv#106]
The Colagrossi dambreak problem has slip conditions at the walls of the tank based on the input files, but the README says they are no-slip.

**Comment by adimako** [comment]
Chris, just fixed that.

**Comment by cekees** [comment]
OK, dambreak validation problems usually use slip conditions, right? We've done it both ways, but I don't recall the no-slip condition being very useful at this scale.

**Comment by adimako** [comment]
No-slip condition will affect some small features, like the leading edge but should not change the bulk of the flow.
