### ISSUE TITLE
List of 2D Tests to Refactor

### ISSUE THREAD

**Issue by nerisaurus** [erdc-cm/air-water-vv#110]
WIP

@adimako @tridelat @Giovanni-Cozzuto-1989 @cekees 
In order to make sure we cover all the tests, here is a list of all 2D air-water-vv tests I am paying attention to.  I will try to refactor everything listed here to the new best practices we have, but I might be slower or less effective, especially with tests that you are particularly familiar with.  I will try to make sure to post responses to this issue in particular to update you on which tests I'm working on (as well as updating the sub-issues).

Please contribute - in particular, add tests that aren't in this list with links (I'll explain the structure of these issues below), and update my references if you've adjusted or updated tests in other branches.  It can be hard to tell which branches are "ahead" or "behind" in their implementation of a particular test, but it's always nice to be working off of more modernized work.

The format I'm currently using to lists tests is as follows:

> ## Category
> 
> The broad category of the issue, with a brief description of what classifies a problem as being in that category.
> ### Test
> 
> A series of problems that follows one physical problem and has one set of code to support it.  Ideally, each can be covered by one set of modules with only context option changes to differentiate sub-tests.  Each should have some form of readme or explanation which describes the problem at this level, gives insight to call the functions, and maybe talks about the different sub-tests if they are important.  Each should link to the readme to help explain what the test's physical needs are.
> - [x] Geometry: _what shape(s) from SpatialTools are needed to support this test, including any variations or special adjustments needed for the problem and sub-tests.  If this shape is already well supported, this box is checked._
> - [x] Main Code: _checked if there is updated clean code that can run at least one sub-problem and has context options (there might need to be refactoring to match all the other sub-tests, of course)_
> 
> Variant Options
> 
> > - [x] **Variant** ([last version]).  _A sub-test.  The [last version] link should go to the most updated and clean implementation of this particular sub-test that we have, to easily check how it set up parameters and what made it different.  These will generally be taken care of by having a separate context file which can be used to set all the context options to its default values - once this is made and tested, the box can be checked._
> 
> Comments
> 
> > _Additional comments on the Test can go here, prefaced by names to help keep track of them._

So in general it goes 

`parun ./air-water-vv/2d/Category/Test_so.py -C "Variant_Options_File" -o "other changes"` 

(not that you'd run parun that way usually, but that illustrates the file structure).

I've subdivided this issue based on the directory structure in the refactoring branch.  You can also comment here on new folders you think should be split off, or any movement of tests from one category to another.
- [Benchmarks:](https://github.com/erdc-cm/air-water-vv/issues/111)
- [constantSlopeBeach:](https://github.com/erdc-cm/air-water-vv/issues/116)
- [floatingStructures:](https://github.com/erdc-cm/air-water-vv/issues/112)
- [hydraulicStructures:](https://github.com/erdc-cm/air-water-vv/issues/113)
- [numericalTanks](https://github.com/erdc-cm/air-water-vv/issues/114)
- [other](https://github.com/erdc-cm/air-water-vv/issues/115) (as these categories hold only a couple tests each)

**Comment by adimako** [comment]
@nerisaurus:
- flat_linear_waves: To be removed and stay as an archived branch, as now replaced by numericalTanls/linearWaves
-nonlinear flat waves: Same here, to be replaced by nonlinear flat waves
-reflecting flat waves: to be replaced by standingWaves
-Xie and Chen @cekees I think this is goes under the constant slope tests unless it is a submerged bar

**Comment by nerisaurus** [comment]
Now that I'm back where I can check my previous simulations of the two I think Chen has a submerged bar, but Xie does not, so I'll move them accordingly unless there's other input.

For the others, are the[ linear wave ](https://github.com/erdc-cm/air-water-vv/blob/798cb080091347ceb5247e03f8efa90d98cb3146/2d/linear_waves_flat/linear_waves_flat_01/README.rst)and [nonlinear wave](https://github.com/erdc-cm/air-water-vv/blob/798cb080091347ceb5247e03f8efa90d98cb3146/2d/non_linear_waves_flat/README.rst) readme's still good to use as references for the new problems?

**Comment by nerisaurus** [comment]
I've pushed a branch in Proteus that contains the code I'm using to support the air-water-vv changes I make (mostly changes to SpatialTools which allow calls from the tests to resolve properly) [here](https://github.com/erdc-cm/proteus/tree/nneri/refactor_support).  It's a bit messy, and I'll split pieces off of it and clean them up when I actually push for the functionality to be merged into Proteus.  For now I just have it up so I'm not making mysterious unsupported calls in my code.  Feel free to merge in new support there, or to mention new functionality that I'll want to merge in to make sure my proteus work stays compatible.

Meanwhile, I will be focusing on starting to port over changes in the hydraulicStructures category in a branch [branch pending - come back later for a link].

**Comment by nerisaurus** [comment]
I've actually diverted from my main focus to try to update the Numerical Tank problems to the latest cython boundary condition updates, so that I have code that runs to test things out with (as I can't find a local commit where they will run).  

@tridelat , I followed your advice [here](https://github.com/erdc-cm/proteus/pull/397#issuecomment-232447301) on updating numericalTanks/nonlinearWaves to the new standard, but I keep running into this problem:
```
  File "/home/chluser/proteus/linux2/bin/parun", line 10, in <module>
    execfile(__file__)
  File "/home/chluser/proteus/scripts/parun", line 478, in <module>
    runName + '_init_prof')
  File "/home/chluser/proteus/proteus/Profiling.py", line 190, in __call__
    return func(*func_args, **func_kwargs)
  File "/home/chluser/proteus/proteus/NumericalSolution.py", line 468, in __init__
    model = Transport.MultilevelTransport(p,n,mlMesh,OneLevelTransportType=p.LevelModelType)
  File "/home/chluser/proteus/proteus/Transport.py", line 6003, in __init__
    PhiSpaceTypeDict=phiSpaces)
  File "/home/chluser/proteus/proteus/Transport.py", line 6229, in initialize
    movingDomain=movingDomain)
  File "/home/chluser/proteus/proteus/mprans/RANS2P.py", line 1171, in __init__
    diffusiveFluxBoundaryConditionsSetterDictDict)
  File "/home/chluser/proteus/proteus/mprans/RANS2P.py", line 75, in __init__
    getDiffusiveFluxBoundaryConditions,getPeriodicBoundaryConditions)
  File "/home/chluser/proteus/proteus/NumericalFlux.py", line 1997, in __init__
    getDiffusiveFluxBoundaryConditions,getPeriodicBoundaryConditions)
  File "/home/chluser/proteus/proteus/NumericalFlux.py", line 1788, in __init__
    parallelPeriodic=True)
  File "/home/chluser/proteus/proteus/NumericalFlux.py", line 168, in __init__
    g = gReturn[0]
AttributeError: BoundaryCondition instance has no attribute '__getitem__'
```
Any insight on this?  The code at the point I get this error is up [here](https://github.com/erdc-cm/air-water-vv/tree/nneri/refactor/cython_compatibility) if anyone wants to try it out.

**Comment by tridelat** [comment]
It looks like the boundary conditions are not initialised and that a BoundaryCondition class instance is passed instead of the actual function(x,t), you have to add `init_cython()` (e.g. `domain.bc[flag].p_dirichlet.init_cython()`) in all your `*_p.py` files?

**Comment by nerisaurus** [comment]
I had indeed missed some of those (I think I had put them in on an earlier more ambitious refactoring [trying to deal with import statements too, which brought up too many bug], and forgot to redo them when I retreated to this refactor).  That seems to get past that bug (and into another, of course, but one that I recognize already).

**Comment by nerisaurus** [comment]
After some bug fixing which @tridelat helped with a lot, I have made a crude compatibility update for the numerical tank tests ([branch here](https://github.com/erdc-cm/air-water-vv/tree/nneri/refactor/cython_compatibility)).  I've only tested it on nonlinear waves so far, so I'm not eager to merge it in yet - and the fixes are not particularly clean at all points (although I did try to also clean up a few imports and error messages along the way) - but it's a start. Once I've done a few more tests, I'll move back to the hydraulicStructures.

**Comment by nerisaurus** [comment]
Current work is on benchmarks (some hydraulicStructures code is bringing up obscure errors, and the dambreak problems in particular provide a series of stepping stones to test solutions as each new complicating element gets added to the problem - while at the same time getting more tests refactored), with my current rough work [here](https://github.com/erdc-cm/air-water-vv/tree/nneri/refactor/benchmarks).

**Comment by nerisaurus** [comment]
Pull request #119 is a nearly complete update for the four benchmark problems (with dambreak considered a derivative of dambreak_Ubbink).
