### ISSUE TITLE
Refactoring Tests: Benchmarks

### ISSUE THREAD

**Issue by nerisaurus** [erdc-cm/air-water-vv#111]
See the main issue ( #110    ) for explanation
## Benchmarks

A folder for short and simple test cases which simulate a fundamental process and don't need to fit into another category.
### Dambreak without an Obstacle (Colagrossi)

Water collapses in a rectangular tank with no objects ([readme](https://github.com/erdc-cm/air-water-vv/blob/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Colagrossi/README.rst)). Open top, free slip elsewhere.
- [x] Geometry: Tank2D
- [x] Main Code:

Variant Options

> - [ ] **coarse** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Colagrossi/dambreak_Colagrossi_coarse))
> - [ ]  **medium** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Colagrossi/dambreak_Colagrossi_medium))
> - [ ]  **medium R 40** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Colagrossi/dambreak_Colagrossi_medium_R_40))
> - [ ]  **fine** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Colagrossi/dambreak_Colagrossi_fine))
> - [ ]  **structured** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Colagrossi_structured/dambreak_Colagrossi_medium_R_40_structured)) based off of _medium R 40_

Comments:

> @nerisaurus : I would plan to make all the different refinements as context files, but have the structured case just be supported as a context option (so using the default file of context options for _medium R 40_ plus switching `structured = True` as a context option would get the structured case).
### Dambreak with an Obstacle (Ubbink)

Water collapses in a rectangular tank and strikes a small obstacle in the floor ([picture](https://raw.githubusercontent.com/erdc-cm/air-water-vv/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreakUbbink.bmp) [readme from dambreak](https://github.com/erdc-cm/air-water-vv/blob/refactor_air_water_vv/2d/benchmarks/dambreak/README.rst)). Open top, free slip elsewhere?
- [x] Geometry: A 2D tank with an attached obstacle
- [x] Main Code:

Variant Options

> - [ ] **coarse** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Ubbink_coarse))
> - [ ]  **medium** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Ubbink_medium))
> - [ ]  **fine** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Ubbink_fine))
> - [ ]  **fine ptc** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Ubbink_fine_ptc))
> - [x]  ~~**fine updated SGS** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/dambreak_Ubbink_fine_updated_SGS))~~ _see @adimako's comment_

Comments:

> @nerisaurus: Same as above. 
### Quiescent Water Probe

Water in a rectangular tank.  Free slip with an open top?
- [x] Geometry: Tank2D
- [x] Main Code:

Variant Options

> - [ ] **quiescent water probe** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/quiescent_water_probe_benchmark))

Comments:

> @nerisaurus Same here. This is a very useful benchmark for verifying any improvements we do for data acquisition as it is fast. Needs a decent mesh refinement but not sensitivity analysis
> ### Wavesloshing
> 
> Water in a rectangular tank, starting with a sloped free surface to induce linear sloshing ([readme](https://github.com/erdc-cm/air-water-vv/blob/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/wavesloshing/README.rst))
> - [x] Geometry: Tank2D
> - [x] Main Code:

Variant Options

> - [ ] **coarse** ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/wavesloshing/wavesloshing_unstruct/wavesloshing_unstruct_coarse))
> - [ ] **medium**  ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/wavesloshing/wavesloshing_unstruct/wavesloshing_unstruct_medium))
> - [ ] **fine**  ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/wavesloshing/wavesloshing_unstruct/wavesloshing_unstruct_fine))
> - [ ] **structured**  ([last version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/benchmarks/wavesloshing/wavesloshing_struct/wavesloshing_struct_fine)) based off of _fine_

Comments:

> @nerisaurus : My plan would be to give fully fleshed out context files for the three unstructured versions, but have a context option for "structured".  Calling it with `-C "models/default_fine" -o "structured=True"` (not with those exact names or syntax, but that general idea) should get the prebuilt structured case.  The different refinements may or may not be eventually removed as separate option files as well.

Comments

**Comment by adimako** [comment]
@cekees @nerisaurus I would remove any tests with the SGS model as there are 2D cases and we should not be using this turbulence model
