### ISSUE TITLE
Refactoring Tests: Numerical Tanks

### ISSUE THREAD

**Issue by nerisaurus** [erdc-cm/air-water-vv#114]
See the main issue ( #110 ) for explanation
## Numerical Tanks

A folder for rectangular tanks with waves. 
### linear waves

The waves in the tank are linear.
- [x] Geometry: Tank2D with modifications
- [x] Main Code
### nonlinear waves

The waves in the tank are nonlinear.
- [x] Geometry: Tank2D with modifications
- [x] Main Code
### standing waves

Standing waves in a flume.
- [x] Geometry: Tank2D with modifications
- [x] Main Code
### solitary waves

A solitary wave is generated in a flume. ([readme](https://github.com/erdc-cm/air-water-vv/blob/master/2d/solitary_wave/README.rst))
- [x] Geometry: Tank2D with modifications
- [ ] Main Code
### steady current

A flume like the others, but this just has a uniform horizontal velocity. ([readme](https://github.com/erdc-cm/air-water-vv/blob/master/2d/steady_current/README.rst))
- [x] Geometry: Tank2D with modifications
- [ ] Main Code

**Comment by adimako** [comment]
@nerisaurus, I think wave tank generic should be removed. The solirary waves should be integrated to the waveTools module and produce a variant. Same for steady current
