### ISSUE TITLE
Refactoring Tests: All the Other Ones

### ISSUE THREAD

**Issue by nerisaurus** [erdc-cm/air-water-vv#115]
See the main issue (#110) for explanation.

_These categories are a little more specific or simply don't have a lot of tests in them yet, so I've condensed the concept of category and test into one header for many in this list._
## Caisson Breakwater

A caisson in a tank.  I'm not sure just from a brief introspection about the shapes involved, so I'll get back to that part later.  No readme provided.
- [ ] Geometry: Currently a custom setup involving a lot of CustomShape use, which may be preventable.
- [ ] Main Code: 

Variant Options

> - [ ] **caisson breakwater** ([latest version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/caissonBreakwater/fixed))

Comments

> .
## Moving Cylinder

A cylinder moving (well, a moving domain) in a half filled tank.
- [ ] Geometry: 
- [ ] Main Code: 

Variant Options

> - [ ] **moving cylinder** ([latest version](https://github.com/erdc-cm/air-water-vv/tree/master/2d/moving_cylinder))

Comments

> .
## Rubble Mound Breakwaters

Water flowing over a porous obstacle.
- [ ] Geometry: currently a custom shape.
- [ ] Main Code: _looks pretty solid, but may need a tiny bit of refactoring in the end_

Variant Options

> - [ ] **submerged** ([latest version](https://github.com/erdc-cm/air-water-vv/tree/32ff00e77712addc8953484fb1d1f21bf947d3b8/2d/rubbleMoundBreakWater/submerged))

Comments

> .
## Submerged Bar

Water waves flowing over a submerged obstacle. 
### nonlinear wave shoaling (Dingeman's)

Nonlinear waves pass over a submerged obstacle on a sloped surface ([readme](https://github.com/erdc-cm/air-water-vv/blob/a195ad8668c7d6635155cf59596cc467ae3264db/2d/submergedBar/Dingemans_wave_shoaling/README.rst))
- [x] Geometry: probably needs an adaption of the sloped shore tank's used in the constant sloped problems
- [ ] Main Code:

Variant Options

> - [ ] **main** ([latest version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/submergedBar/Dingemans_wave_shoaling/Dingemans_wave_shoaling_01))
> - [ ] **GAZ** ([latest version](https://github.com/erdc-cm/air-water-vv/tree/a195ad8668c7d6635155cf59596cc467ae3264db/2d/submergedBar/Dingemans_wave_shoaling/Dingemans_wave_shoaling_01_GAZ))

Comments

> .
### Waves, Chen

Waves over a submerged bar on a slope. ([readme](https://github.com/erdc-cm/air-water-vv/blob/47d2d99f3ae9f23a1cec42f92ed72c2ff8cf81fd/2d/waves_Chen/README.rst))
- [x] Geometry: probably the same adaption of the sloped shore's tank
- [ ] Main Code

Variant Options

> - [ ] **coarse** ([latest version](https://github.com/erdc-cm/air-water-vv/tree/47d2d99f3ae9f23a1cec42f92ed72c2ff8cf81fd/2d/waves_Chen/tank_coarse))
> - [ ] **medium** ([latest version](https://github.com/erdc-cm/air-water-vv/tree/47d2d99f3ae9f23a1cec42f92ed72c2ff8cf81fd/2d/waves_Chen/tank_medium))
> - [ ] **fine** ([latest version](https://github.com/erdc-cm/air-water-vv/tree/47d2d99f3ae9f23a1cec42f92ed72c2ff8cf81fd/2d/waves_Chen/tank_fine))

Comments

> .

**Comment by adimako** [comment]
Maybe "all the others" should fall under a "WSI" folder
