### ISSUE TITLE
ecH and other naming conventions

### ISSUE THREAD

**Issue by nerisaurus** [erdc-cm/air-water-vv#120]
I originally commented on this on a commit in a pull request, but since that's buried a bit I'll bring it up here.

So we tend to have code in the form:

```
    epsFact_density = epsFact_viscosity = epsFact_curvature \
                                 = epsFact_vof = ecH \
                                 = epsFact_consrv_dirac \
                                 = 3.0
    epsFact_redistance = 0.33
    epsFact_consrv_diffusion = 0.1
```

where `ecH` used to be `epsFact_consrv_heaviside` - but must be `ecH` for the purposes of boundary conditions [0], which picks it up via the Context module.  This mixed naming convention is awkward, and will become more awkward over time as other names and their references might morph or be separated from each other.

What should we name these variables?  
- Avoiding the need to have a fixed name sounds like a good idea, but would require a new technique for managing boundary condition information.  We also have a lot of commonly used variables that a lot of functions are interested in across modules, so the future probably involves more fixed names (hopefully cut up into bite sized classes and clusters of variables which are explicitly set and explicitly called on [1], but this will still require us to figure out naming conventions that stick and work together).
- We could go back and force boundary conditions to take `epsFact_consrv_heaviside`, which seems to be the dominant notation in the air-water-vv setting - but this might be a particularly surprising or easily mistaken variable to expect other people to put into their code (and if people can't comfortably set the correct variables to make the code work, they won't end up benefiting from the boundary condition tools).
- We could name everything in the style of `ecH`.  Perhaps:

```
    eD = eV = eC \
           = eVOF= ecH \
           = ecDirac \
           = 3.0
    eR = 0.33
    ecD = 0.1
```

This, however, can be confusing in its own right.  This could have some intuitiveness if it was inside its own cluster of variables, which could be named `epsFact` or an even longer and more descriptive name [2] and maybe have documentation of its own.  Even then this might be too bare bones.
- There's also perhaps other styles in between - stretching out `ecH` but still reducing the size of the other variable names to a length where all of them have descriptive titles.  It could start with extending out to `eps_cH` or `ecHeaviside` or the like, perhaps.  I don't know what everyone thinks works best here.  Again, these would be better in a cluster or class of variables which allows us to use multiple layers of descriptive names, but they might be more viable without it [3].

Any ideas on a good naming scheme for me to propagate through the code?

---

[0] Boundary conditions also force down `he`, but this variable is predominantly already called `he` in the tests, has a common usage as that term outside of proteus, and is a lone variable that has a clear role - while `ecH` is cluttered in a tangle of other parameters that work somewhat as a whole.  I'm not worried about `he` at all - it would be nice to have clear ways of dealing with it (either ways to avoid needing to specify it, or explicitly pinning it down to `he` and clarifying when it gets called outside), but it's fairly safe as it is from my perspective.

[1] That is, instead of implicitly set and called on, as it is now.  A user declares a variable to be `ecH` which silently implies that it should be used in a particular use case in a completely different module triggered by separate code.  Other code just calls in `ct = Context.get()` and implies that certain names need to be there (and this isn't just boundary conditions - the `_n.py` and `_p.py` files do this all over the place, and in turn push some of these concepts into basically every bit of proteus).

What we want would be for be for the user to specifically bring in a cluster of numerical parameters, set them (potentially with default values too, for some values which have "reasonable" values to keep around), and then explicitly bring in that cluster of parameters into another piece of code which needs them.  Every module and function call to these variables would have a clear marking of which cluster it's looking into (rather than just `ct.something`) leading to easier bug fixing and connect the dots code writing.

That's another issue entirely, though.

[2] I don't actually know what "epsFact" stands for, and why it describes all these width defining variables.  Epsilon something?

[3] Which is a good thing because bunching up the variables isn't going to happen immediately.

**Comment by tridelat** [comment]
[0] The best would be to put these variables in a dictionary or group them per theme in different dictionaries (with default values) in my opinion, so they would consistently be called the same across test cases, and only the ones that the user wants to set differently are called. And names should be relatively explicit without being too long. Something that could be accessed like this: (maybe with better categories)
```
n.epsFact['density'] = 3.0 
n.epsFact['redistance'] = 0.33 
n.shockCapturing['vof'] = 0.5
```
Concerning the boundary conditions with `ecH` (which could be renamed `epsFact_consrv_heaviside` in the `BoundaryConditions` module for now if it helps) and `he`, one of the main problem is when there is a variable mesh size (e.g. refined around the free surface with gmsh), because `he` is usually used as a global mesh size constant. Maybe the smoothing "width" around the free surface (`ecH*he`) could be passed as argument to the boundary condition instead.

[1] yes, it is more of a hack right now, this should be improved (a default, modifiable dictionary would help).

[2] I think Fact stands for factor here

**Comment by nerisaurus** [comment]
I'm not sure if a dictionary is the best idea for these variable clusters.  I believe a class is slightly more efficient, especially for a fixed set of inputs (since we shouldn't need to add in a new type of epsFact [0] ) as well as allowing for more ways to set default values (and potentially have multiple sets of defaults [1] ).

It also would be slightly cleaner when using `pdb.set_trace()` and trying to look at all the variables floating around.  It might take a bit of time to learn that you always have to `dir(n.epsFact)` each time you encounter an unfamiliar cluster of variables (to figure out which values are held by epsFact), but if you have a lot of these dictionaries around they can provide too much information in a `locals()` check in some scopes.

Finally, a class gives a space to name the class and give it an informative doc string (that can be found in a `set_trace()` or found while looking at the function in the files) that helps explain what variables should be contained within and why they matter (and what not to do with them).

[0] Or rather, if we do, we should explicitly add it in.  Otherwise one person might add in an `epsFact['new_thing']` for a few tests and then it slowly grows until some functionality becomes reliant on that key existing and we're back in square one of having to declare variables no matter what.  People need to be forced to make the decision of when a variable is part of a group of variables or not, and to figure out its default behavior when adding it.

[1] So say the `epsFact` class sets `self.density = 3.0` by default.  You could specify `n.epsFact.density = 1.5` to change it, or you could say `n.epsFact.setAllTheseMainValues(value=1.5)` for it to set `self.density, self.consrv_heaviside, self.curvature` etc. to 1.5 (obviously the function name should be more explanatory than that).  For parameters which often take certain sets of values for certain types of problems we could have stuff like `n.epsFact.setWaveProblem()` or similar (probably not for epsFact, but maybe for another class).

**Comment by tridelat** [comment]
Yes, a class that would allow to set the options through functions would be nice. 
I started something that looked like this (quite a long time ago, I did not use it), but it might be too many nested dictionaries.
Dictionaries could be replaced by the classes you mentioned if it makes it easier.

```python
class NumericalOptions:
    def __init__(self):
        self.runCFL = 0.9
        self.basis = C0_AffineLinearOnSimplexWithNodalBasis
        self.mesh = {'parallelPartitioningType': None,
                     'nLayersOfOverlapForParallel': None,
                     'restrictFineSolutionToAllMeshes': None,
                     'he': None}
        self.shockCapturing = {'ls': {'factor': None,
                                      'lag': None,
                                      'uref': None,
                                      'beta': None},
                               'vof': {'factor': None,
                                       'lag': None,
                                       'uref': None,
                                       'beta': None},
                               ...
                               }
        self.epsFact = {'density': None,
                        'viscosity': None,
                        'vof': None,
                        'consrv_heaviside': None,
                        'consrv_dirac': None,
                        'redistance': None,
                        'consrv_diffusion': None}
        ...
```

then, in the _n files, it could be accessed (`n` being the `NumericalOptions` class):
```python
shockCapturingFactor=ct.n.shockCapturing['vof']['factor']
```
so it forces the user to use the predefined variables/keys in the `NumericalOptions` class to set new values in his main file.

This could use global functions such as `setAllShockCapturingFactor(value=1.5)` or dictionaries could be replaced by classes as you described and have their own functions.

**Comment by nerisaurus** [comment]
I do like the look of the dictionary setup, although of course it will only involve more nested layers in practice.  I think classes will be easier to access, though.

`shockCapturingFactor = ct.n.shockCapturing.vof.factor`

follows a more standard object oriented notation.  As well as the benefits I mentioned earlier, this means that tools which read the code (autocompletion in IDE's or plugin-aided text editors, error trace back, checking for mispelled class names, etc.) will understand it.  Since dictionaries are changeable, I don't think any tool will track them well (and while the class-holding-clearly-listed-dictionaries we have above might discourage changing it, someone can still say `ct.n.shockCapturing['vof']['new_factor'] = 1.0` and use it as a short cut - or just mess up and make `ct.n.shockCapturing['vof']['fctor'] = 1.0`)

It also means each level* can have its own doc string and functions, which can be found by a user using `dir([that level of the code])` within its clear use case.  They also can have their own initialization, which could include input checks if desired.

There is also the `namedtuple` data type from `collections`, which I've noticed used in a couple places in code, which generates simple container style classes in a relatively easy to use manner.  I don't really like its notation and I'm not sure if all tools will be smart enough to understand its usage (plus, it's`dir()` is a bit messier because it tries to work as a dictionary and as a list as well as like a class), but it might make sense for quickly making a few simpler ones.

There might also be techniques to use the tools `namedtuple` uses to make a class-generating-tool that works better for our needs.

**Comment by tridelat** [comment]
I agree with this and also prefer the class based approach to access variables (`ct.n.shockCapturing.vof.factor` or `ct.n.shockCapturing.factor.vof` or else), enabling autocompletion and other functionalities. It is true that it is extra work to implement, but if it makes accessing numerical parameters more intuitive and helps documenting it easily, it must be the way to go.
