### ISSUE TITLE
Solitory wave

### ISSUE THREAD

**Issue by yuxianglin** [erdc-cm/air-water-vv#128]
Hi,

I am having problem in running the 2D solitary wave demo case, I see that in the tank.py file, the mesh size is equal to the wave amplitude,https://github.com/erdc-cm/air-water-vv/blob/master/2d/solitary_wave/solitary_wave_01/tank.py#L83,  however by this setting we cannot visualize the wave propagation, the wave is within one mesh size area, is there any specific reason to set the mesh size like this?

In addition, while I set a higher solitary wave height, it is found the wave diffuse quickly as it propagate. It is well known the solitary wave could maintain its shape while propagate, what is reason that diffuse so quickly?

Furthermore, what is the trans mean in https://github.com/erdc-cm/air-water-vv/blob/master/2d/solitary_wave/solitary_wave_01/tank.py#L363, it seems it needs to take some argument.

Any advise would be appreciated.

**Comment by adimako** [comment]
Hi @yuxianglin, 

>  am having problem in running the 2D solitary wave demo case, I see that in the tank.py file, the mesh size is equal to the wave amplitude,https://github.com/erdc-cm/air-water-vv/blob/master/2d/solitary_wave/solitary_wave_01/tank.py#L83, however by this setting we cannot visualize the wave propagation, the wave is within one mesh size area, is there any specific reason to set the mesh size like this?

The flow depth that you have to discretize efficiently in the solitary wave is (d+H) where d is the depth and H is the height. I would recommend using at least 20 points over this length, and in this case, as H ~ 1/20 of the depth, mesh size and H coincide. I understand that H=0.05 corresponds to a low amplitude wave so it will be difficult in visualising anyway, but that does not mean that the results are wrong. You can use other variables to assess mesh refinement like pressure. You can start adding points along the wave height later on, to make videos and pictures nicer, but I doubt that the actual accuracy will be significantly increased

> In addition, while I set a higher solitary wave height, it is found the wave diffuse quickly as it propagate. It is well known the solitary wave could maintain its shape while propagate, what is reason that diffuse so quickly?

As said, you have to keep he ~ 1/20. If you switch to a higher amplitude (e.g. say 0.2 m) then keeping the mesh size 0.2 m will result in an extremely coarse refinement, hence the dissipation. I would recommend to use a maximum size of 0.05 m and start reducing if results are dissipating

>Furthermore, what is the trans mean in https://github.com/erdc-cm/air-water-vv/blob/master/2d/solitary_wave/solitary_wave_01/tank.py#L363, it seems it needs to take some argument.

trans is the position of the wave peak. It should be defined somewhere as I do not find it. Have you tried defining it?

Note that this format corresponds to an old version of the software and we have moved forward in v1.2.1, however we have not yet changed the layout of this cases (this is work in progress). If you want to see an example of a new layout for numerical tank set-up, see https://github.com/erdc-cm/air-water-vv/tree/nneri/refactor/numericaltanks/2d/numericalTanks. We do not have a solitary wave there but we would be more than happy to assist you in setting one if needed

**Comment by yuxianglin** [comment]
Thank you for your reply @adimako 

> As said, you have to keep he ~ 1/20. If you switch to a higher amplitude (e.g. say 0.2 m) then keeping the mesh size 0.2 m will result in an extremely coarse refinement, hence the dissipation. I would recommend to use a maximum size of 0.05 m and start reducing if results are dissipating

Forget to mention, I am setting a higher wave height(H=0.2m) with the same mesh size(he=0.05), the wave dissipated quickly as it propagates.

> trans is the position of the wave peak. It should be defined somewhere as I do not find it. Have you 
tried defining it?

I am a bit confused with this, the wave height is the height corresponding to the x, therefore should be H*sech^2(k*(vt-x[0])), why we need to add a trans?

**Comment by adimako** [comment]
@yuxianglin, I see. Do you have any snapshots from the numerical domain (including mesh refinement)? Can you check if the crest of the wave is too close to the atmosphere boundary?

Trans is just a variable to translate the peak at t=0. For t=0, the maximum peak will be at x=0 if trans is not set. If you set trans, then for t=0, the peak will be at x=trans

**Comment by yuxianglin** [comment]
![solitary_wave](https://cloud.githubusercontent.com/assets/17280119/23275027/7e89d99e-f9ca-11e6-8e1d-d9c1e63e733a.png)
![solitary_wave2](https://cloud.githubusercontent.com/assets/17280119/23275028/7e8bc5a6-f9ca-11e6-82f8-60108808938d.png)
![solitary_wave3](https://cloud.githubusercontent.com/assets/17280119/23275026/7e8951fe-f9ca-11e6-9942-46af77c9cabe.png)

Here is the snapshot for the solitary wave, note that I have reduced the tank length to 20 and set the waterdepth to 0.8, wave height to 0.2 while maintain the he to 0.05, and set the trans=0.

The solver for this case is quiet unstable, by reducing further mesh size or water depth would result in solver failure.

**Comment by yuxianglin** [comment]
![solitary_wave4](https://cloud.githubusercontent.com/assets/17280119/23278411/091d5b1a-f9d7-11e6-9626-89ad0f150cce.png)
![solitary_wave5](https://cloud.githubusercontent.com/assets/17280119/23278412/092bc862-f9d7-11e6-8d3d-7785edd15f27.png)
![solitary_wave6](https://cloud.githubusercontent.com/assets/17280119/23278413/092ecac6-f9d7-11e6-833b-46283988ff97.png)

**Comment by adimako** [comment]
@yuxianglin, I see. Try using trans and let the solitary wave further in by setting trans=10 for example to see if this it improves things. But I am afraid that this case is quite old. I will speak with the team to implement the solitary wave equations for one of the new tanks that we use for regular waves.

**Comment by yuxianglin** [comment]
Hi, @adimako I have a question for the wave generation for proteus.

I saw there is a wave generation and absorption zone implemented in the proteus, I wondered how to do they helped to generate the wave?

In addition, regarding to solitary waves, or other types of wave, we need to specify its two phase velocity u, v. For small amplitude and linear waves, they may have analytical soln.  But for large amplitude, solitary waves,  it is difficult to obtain the two phase velocity as boundary condition. How to generate these wave? Does the sponge layer help in generating these waves?

**Comment by adimako** [comment]
@yuxianglin Yes, the sponge layer is helping. As said, these are quite old cases, we have moved on to a different configuration. We do use sponge layers as they help generate and absorb the wave, but I suppose this old case was using them as well. It is just that any analytical solution for waves now has to go through the WaveTools.py module (https://github.com/erdc-cm/proteus/blob/master/proteus/WaveTools.py).

Yesterday I pushed the analytical solution for the solitary wave and I will be pushing a test case later on that hopefully will work better than this one. The solution is 1st order, and when the amplitude is large, you are right the solution will not be strictly valid, but if the wave does not break at the boundary or inside the sponge layer it will eventually create the correct profile.

**Comment by adimako** [comment]
@yuxianglin try the case from this branch. https://github.com/erdc-cm/air-water-vv/tree/adimako/solitaryWave/2d/solitary_wave. This case is better because 

I) You can change options from the dictionary in the beginning of tank.py
ii) It uses the numerical parameters which have been observed to show good performance and avoid silly issues like the ones you have been noticing. I also think that the vertical velocity in that old case was not quite right

I run the case with a coarse mesh and I am showing the results further below

**Comment by adimako** [comment]
![capture](https://cloud.githubusercontent.com/assets/8258298/23406830/ded9eb3a-fdb8-11e6-8329-7108b90279b8.JPG)

**Comment by adimako** [comment]
@yuxianglin This is taken from my dashboard. I run the case with he=0.1 which is admittedly too coarse and then with he=0.05, which I am showing, so the only difference with the case I have uploaded is he. On the right there is the flume with the free surface and the left the pressure at the bottom at t=3.1 sec. 
As you see the free-surface appears noisy, but this is something that we have observed consistently and we think it is rather a visualisation than a numeric issue. There is an instability developing at the tail of the solitary wave, this might be either because we need to use a higher order relation, or because the initial pressure, which is hydrostatic, is an approximation.

I'd rather you used this case if you want to check mesh sensitivity etc. and feel free to report any more issues

**Comment by yuxianglin** [comment]
Hi @adimako 

Thank you for your update in git hub, I 've downloaded the solitary wave, and ran at a higher amplitude which works fines.

I have a question related to my research topic, it is when solitary wave hit a obstacle in 3D, I saw the in mpran/Spatialtool.py there is a tank2Dwithobstacle class which inheritate from tank2D, is it a good idear to also create a class tank3Dwithobstacle class also, to create that tank object?(actually I could by create vertex, segment, face and etc to domain.py to create the mesh, but the new version seems to attach the bc and ic to the tank in the spatialtools )

Any advise would be appreciated.

Yuxiang

**Comment by adimako** [comment]
@yuxianglin, thanks.

Maybe it is worth waiting @tridelat to give us a view on your question, as he is the lead developer behind Spatialtool.py

**Comment by tridelat** [comment]
@yuxianglin, you can use the `CustomShape` class from `SpatialTools` (mprans) to build an entire domain by giving vertices, segments, flags, etc. and get the BCs attached to it (you need to pass a `boundaryTags` dictionary when creating the shape in order to get the BCs populated). 
You will want to use the `add_gmsh_support` branch (https://github.com/erdc-cm/proteus/pull/432) as their was a typo in `CustomShape` that has been fixed there. Otherwise, modify https://github.com/erdc-cm/proteus/blob/master/proteus/SpatialTools.py#L535 `self.boundaryTgs` to `self.boundaryTags` in your proteus installation, and recompile if necessary.

Alternatively, you can also create a class in `SpatialTools` if you think it could be useful

The ICs are usually not attached and need to be set separately in the `_p.py` files.

**Comment by yuxianglin** [comment]
@tridelat Thank for your reply.

It seems I still need to add sponge layers to the customshape class in proteus.mprans.spatialtools like you add to tank2D/3D

**Comment by yuxianglin** [comment]
@tridelat Thank for your reply.

It seems I still need to add sponge layers to the customshape class in proteus.mprans.spatialtools like you add to tank2D/3D, as my domain need wave generation and absorption at x- and x+ to generate solitary wave

**Comment by yuxianglin** [comment]
@tridelat Thank for your reply.

I've delete the previous comment.

I saw that the shaperans class already have generation and absorption zone built in, thanks.

**Comment by yuxianglin** [comment]
Hi, @tridelat 

I am wondering in customshape class in Spatialtool.py, why isn't there a facetHoles input in the __init__, which need to specify for the 3D shape construction?

**Comment by tridelat** [comment]
@yuxianglin , if I recall well, you need to define your facets this way:

```python
facets = [ [[0, 1, 2, 3], [4, 5, 6, 7]], [[10, 11, 12, 13]] ]
```

Here you have 2 facets defined, with the first one (`[0, 1, 2, 3]`) having a hole facet (`[4, 5, 6, 7]`). You basically put the hole facets after the main vertices of the facet around it.

**Comment by yuxianglin** [comment]
Hi, @tridelat 
All right, this makes sense. 

I am following the Domain.PiecewiseLinearComplexaDomain where facetHoles is also an input for the shape construction.

Thanks for your reply.

**Comment by tridelat** [comment]
I don't know if you need it but if you use `PieceWiseLinearComplexDomain` directly, you will not be able to use the optimised boundary conditions and relaxation zones (wave generation/absorption) easily. If `facetHoles` is something you would like to be added, this can be easily done.
I will push a branch tomorrow.
Meanwhile, it is still possible to use `CustomShape`, assemble you domain, and add the `facetHoles` to your domain manually (`domain.facetHoles = ....`), so you still get access to the mprans BC.

**Comment by yuxianglin** [comment]
Yeah, cause I am constructing a 3D tank with an obstacle inside, PieceWiseLinearComplexDomain is a better choice.

Still I am following the solitary wave case and use the Spatialtools.customShape for domain construction, attach BC to the tank as what is did in solitary/tank.py and make it 3D.

By the way, would you mind telling me how the BC and relaxation zone being optimized, so that I could take a look at it and see how I could make use of it by using PieceWiseLinearComplexDomain class ?

Best,

**Comment by tridelat** [comment]
`CustomShape` in `SpatialTools` and several other other geometries are not specific to 2D domains. You can use a `PiecewiseLinearComplexDomain` and still create a Shape for convenience, as follows:

```python
from proteus import Domain
from proteus.mprans import SpatialTools as st

# initialise domain
domain = Domain.PiecewiseLinearComplexDomain()

# create shapes (sent automatically to your 3D domain)
boundaryTags = {'my_tag1': 1, 'my_tag2': 2, ...}
my_custom = st.CustomShape(domain=domain, vertices=vertices, boundaryTags=boundaryTags, ...)

# assemble domain after creating all geometries
st.assembleDomain(domain)
# add facetHoles to your Domain
# (will be added as an argument to CustomShape in future)
domain.facetHoles = ...

# manipulate BCs
my_custom.BC['my_tag1'].setNoSlip()
my_custom.BC['my_tag2'].u_dirichlet.uOfXT = lambda x, t: 3*t
...
```


The BC and relaxation zones are optimised through cython (converting python code to C), which makes it much faster when iterating over nodes. This can make a big difference especially in the case of relaxation zones as they take up a large part of the domain and therefore require expensive iterations to apply a source term gradually.

You can see the implementation from the files https://github.com/erdc-cm/proteus/blob/master/proteus/mprans/BoundaryConditions.pxd and https://github.com/erdc-cm/proteus/blob/master/proteus/mprans/BoundaryConditions.py
The .pxd file is the one that allows the conversion from python to C++.

It would also be possible to create a function that populates a Domain with (mprans) BC classes so you can directly create a Domain and still use tags and flags to access optimised BC. This can be added in the future, but using the technique above achieves the same, and allows you to create different shapes and add them to a 2D or 3D Domain easily.
