### ISSUE TITLE
Add extraction of  level sets along line gauge

### ISSUE THREAD

**Issue by cekees** [erdc-cm/air-water-vv#7]
We need this to properly do a wave height gauge.  The line gauge produces an array that includes the value of the signed distance  to  the free surface at a set of points along a line. We need to find the intervals where the signed distance changes signs, and then interpolate within that to get  a height. In most cases it only makes sense to do this when that happens once, otherwise the wave is breaking at the gauge and there will be 3 or more free surface  locations. We should probably just grab the highest value in a multivalued setting.

**Comment by adimako** [comment]
Probes are generally robust at this time so I am closing this
